### ISSUE TITLE
How to use --func-annot

### ISSUE THREAD

**Issue by aslangabriel** [gem-pasteur/Integron_Finder#106]
**Describe your problem**
I want to test the annotation function with customized hmm database, 
**To Reproduce**

1. Download the latest AMR.LIB 

2. run the docker editon with the command 
docker run -v $PWD:/home/IF  --user $(id -u):$(id -g) 431219fdaa50 --func_annot /home/shpc_1100038/AMR.LIB --local-max --circ --keep-tmp JSAHVC25.fasta
The error information was listed as follows:
<img width="705" alt="2" src="https://user-images.githubusercontent.com/46910288/197701894-db726673-00b6-443b-9e18-97a0dff86ba7.png">
Thanks a lot

***OS:*** 

 Linux
 

***Integron_Finder Version:***

V2.0

**Additional context**

**Comment by jeanrjc** [comment]
You need to use `--func_annot` which tells IF whether it runs functional annotation or not and `--path-func-annot` with a file containing path to your library. Because `func_annot` does not expect an argument, IF thinks that the path to your lib is the replicon, and thus fails. Besides, it seems the path to your lib is wrong. (`no such file or directory`)

You can read more here :
https://integronfinder.readthedocs.io/en/latest/user_guide/tutorial.html#functional-annotation
